---
title: "Trend analysis"
author: "Timo Kelder"
date: "November 13, 2019"
output: github_document 
---
  
```{r eval=FALSE, include=FALSE}
Rscript -e "rmarkdown::render('Trend_analysis.Rmd')"
```

###Import data and packages

```{r message=FALSE}
dir='//home/timok/timok/SALIENSEAS/SEAS5/ensex'
plotdir=paste0(dir,'/statistics/multiday/plots')
# dir='/home/timok/ensex'
# plotdir='/home/timok/Documents/ensex/R/graphs'
source('Load_data.R')
library(extRemes)
```


```{r}
require(plyr)
names(dimnames(Extremes_WC)) <- c('Member', 'Leadtime', 'Year')
names(dimnames(Extremes_SV)) <- c('Member', 'Leadtime', 'Year')
df_WC=adply(Extremes_WC, 1:3)
df_SV=adply(Extremes_SV, 1:3)
obs=Extremes_obs[as.character(1981:2015)]

year_vector=as.numeric(levels(df_WC$Year))[df_WC$Year]

# fit0 <- fevd(Extremes_WC) #stationair
fit0_WC <- fevd(df_WC$V1) #stationair
fit1_WC <- fevd(df_WC$V1, location.fun = ~ c(df_WC$Year)) #linear loc. The year series is a factor. We are using the factor to classify the years into the values 1:35, for efficiency.  
fit2_WC <- fevd(df_WC$V1, location.fun = ~ c(df_WC$Year),
               scale.fun = ~ c(df_WC$Year), use.phi = TRUE)
fit2_SV <- fevd(df_SV$V1, location.fun = ~ c(df_SV$Year),
               scale.fun = ~ c(df_SV$Year), use.phi = TRUE)
fit2_obs <- fevd(obs, location.fun = ~ c(1:35),
                  scale.fun = ~ c(1:35), use.phi = TRUE) #linear loc


v_wc <- make.qcov(fit2_WC, vals = list(mu1 = c(1:35),phi1 = c(1:35)))
ci_wc=ci.fevd(fit2_WC,type='return.level',return.period = 100,R = 502, method ="normal",qcov=v_wc)  #method=c("normal","boot", 
v_sv <- make.qcov(fit2_SV, vals = list(mu1 = c(1:35),phi1 = c(1:35)))
ci_sv=ci.fevd(fit2_SV,type='return.level',return.period = 100,R = 502, method ="normal",qcov=v_sv)  #method=c("normal","boot", "proflik") -> only normal works :(
v_obs <- make.qcov(fit2_obs, vals = list(mu1 = c(1:35) ,phi1=c(1:35)))
ci_obs=ci.fevd(fit2_obs,type='return.level',return.period = 100,qcov=v_obs)
 
# par(mar=c(4.5,4.5,2.1,0),mfrow=c(1,3),cex.axis=1.5, cex.lab=1.5, oma=c(0,0,0,1))
plot(year_vector,df_WC$V1,xlab=' year',ylab='P (mm)',ylim = c(0,max(ci_obs[,3])),cex=0.2,col=alpha('black',0.4))
points(1981:2015,obs,col='blue',pch=20)
lines(1981:2015,ci_wc[,3],col='orange',type = 'l',lty=2,lwd=3)
lines(1981:2015,ci_wc[,1],col='orange',type = 'l',lty=2,lwd=3)
lines(1981:2015,ci_wc[,2],col='orange',lwd=2)

lines(1981:2015,ci_obs[,3],col='blue',type = 'l',lty=2,lwd=2)
lines(1981:2015,ci_obs[,1],col='blue',type = 'l',lty=2,lwd=2)
lines(1981:2015,ci_obs[,2],col='blue')
legend("topleft", legend=c("20 yr Values", "95% Intervals","Seasonal Extremes"),
       col=c("blue", "blue",'black'), lty=c(1:2,NA),lwd=c(1:2,NA),pch=c(NA,NA,1),pt.cex=1,box.lty = 1,cex = 1.3)


##Svalbard 
plot(year_vector,df_SV$V1,xlab=' year',ylab='P (mm)',cex=0.2,col=alpha('black',0.4))#,ylim = c(0,max(ci_obs[,3])))
#points(1981:2015,obs,col='blue',pch=20)
lines(1981:2015,ci_sv[,3],col='orange',type = 'l',lty=2,lwd=3)
lines(1981:2015,ci_sv[,1],col='orange',type = 'l',lty=2,lwd=3)
lines(1981:2015,ci_sv[,2],col='orange',lwd=2)

```


```{r eval=FALSE, include=FALSE}



par(mar=c(4.5,4.5,2.1,0))
plot(year,Extremes_gev[gridcell,],ylab='P (mm)',cex=0.2)
lines(years,ci00_1[,3],col='blue',type = 'l',lty=2,lwd=3)
lines(years,ci00_1[,1],col='blue',type = 'l',lty=2,lwd=3)
lines(years,ci00_1[,2],col='blue',lwd=2)
lines(years,ci_s[,3],col='orange',type = 'l',lty=2,lwd=3)
lines(years,ci_s[,1],col='orange',type = 'l',lty=2,lwd=3)
lines(years,ci_s[,2],col='orange',lwd=2)
legend("topleft", legend=c("20 yr Values Ensembles", "95% Intervals Ensembles","Ensemble Extremes"),
       col=c("orange", "orange","black"), lty=c(1:2,NA),lwd = c(2:3,NA),pch = c(NA,NA,1),pt.cex=0.2,box.lty = 1,cex = 1.3)



make_plots<-function(Extremes_gev,Extremes_gev00,Extremes_senorge,gridcell){
  fit0 <- fevd(Extremes_gev[gridcell,]) #stationair
  fit1 <- fevd(Extremes_gev[gridcell,], location.fun = ~ c(year-1981)) #linear loc
  fit2 <- fevd(Extremes_gev[gridcell,], location.fun = ~ c(year-1981),
               scale.fun = ~ c(year-1981), use.phi = TRUE)
  v_s <- make.qcov(fit2, vals = list(mu1 = c(1:35),phi1 = c(1:35)))
  v_s_1 <- make.qcov(fit2, vals = list(mu1 = 1,phi1 = 1))
  v_s_35 <- make.qcov(fit2, vals = list(mu1 = 35,phi1 = 35))
  rv0=return.level(fit0,return.period = c(2,20,200))
  rv=return.level(fit2,return.period = c(2,20,200),do.ci=T,qcov=v_s_35,qcov.base=v_s_1)
  rv_2=return.level(fit2,return.period = c(2,20,200),qcov=v_s_1)
  
  v_l <- make.qcov(fit1, vals = list(mu1 = c(1:35)))
  ci_s=ci.fevd(fit2,type='return.level',return.period = 20,qcov=v_s)
  ci_l=ci.fevd(fit1,type='return.level',return.period = 20,qcov=v_l)
    
  rperiods = c(2, 5, 10, 20, 50, 80, 100, 120, 200, 250, 300, 500, 800,2000,5000)
  
  fit00_0 <- fevd(Extremes_gev00[gridcell,]) #stationair
  fit00_1 <- fevd(Extremes_gev00[gridcell,], location.fun = ~ c(as.integer(years)-1981)
                  ,scale.fun = ~ c(as.integer(years)-1981), use.phi = TRUE) #linear loc
  # plot.fevd(fit00_0,'rl',rperiods = rperiods) #ype = c("primary", "probprob", "qq", "qq2", "Zplot", 
  v_s_1_00 <- make.qcov(fit00_1, vals = list(mu1 = 1,phi1=1))
  v_s_35_00 <- make.qcov(fit00_1, vals = list(mu1 = 35,phi1=35))
  rv0_00=return.level(fit00_0,return.period = c(2,20,200))
  rv_2_00=return.level(fit00_1,return.period = c(2,20,200),qcov=v_s_1_00)
  rv_00=return.level(fit00_1,return.period = c(2,20,200),do.ci=T,qcov=v_s_35_00,qcov.base=v_s_1_00)
  
  v_00 <- make.qcov(fit00_1, vals = list(mu1 = c(1:35) ,phi1=c(1:35)))
  ci00_1=ci.fevd(fit00_1,type='return.level',return.period = 20,qcov=v_00)
  setEPS()
  postscript("Documents/ensex/R/graphs/Added_value/Added_value_scale.eps",width = 10,height = 4) #postscript
  par(mar=c(4.5,4.5,2.1,0),mfrow=c(1,3),cex.axis=1.5, cex.lab=1.5, oma=c(0,0,0,1))
  plot(years,Extremes_gev00[gridcell,],xlab=' year',ylab='P (mm)',ylim = c(0,max(ci00_1[,3],Extremes_gev[gridcell,])))
  lines(years,ci00_1[,3],col='blue',type = 'l',lty=2,lwd=2)
  lines(years,ci00_1[,1],col='blue',type = 'l',lty=2,lwd=2)
  lines(years,ci00_1[,2],col='blue')
  legend("topleft", legend=c("20 yr Values", "95% Intervals","Seasonal Extremes"),
         col=c("blue", "blue",'black'), lty=c(1:2,NA),lwd=c(1:2,NA),pch=c(NA,NA,1),pt.cex=1,box.lty = 1,cex = 1.3)
  par(mar=c(4.5,4.5,2.1,0))
  plot(year,Extremes_gev[gridcell,],ylab='P (mm)',cex=0.2)
  lines(years,ci00_1[,3],col='blue',type = 'l',lty=2,lwd=3)
  lines(years,ci00_1[,1],col='blue',type = 'l',lty=2,lwd=3)
  lines(years,ci00_1[,2],col='blue',lwd=2)
  lines(years,ci_s[,3],col='orange',type = 'l',lty=2,lwd=3)
  lines(years,ci_s[,1],col='orange',type = 'l',lty=2,lwd=3)
  lines(years,ci_s[,2],col='orange',lwd=2)
  legend("topleft", legend=c("20 yr Values Ensembles", "95% Intervals Ensembles","Ensemble Extremes"),
         col=c("orange", "orange","black"), lty=c(1:2,NA),lwd = c(2:3,NA),pch = c(NA,NA,1),pt.cex=0.2,box.lty = 1,cex = 1.3)
  
  # lines(years,ci_l[,3],col='orange',type = 'l',lty=2,lwd=3)
  # lines(years,ci_l[,1],col='orange',type = 'l',lty=2,lwd=3)
  # lines(years,ci_l[,2],col='orange',lwd=2)
  
  # plot.fevd(fit0,'rl',rperiods = rperiods) #ype = c("primary", "probprob", "qq", "qq2", "Zplot",
  ci=ci.fevd(fit0,type='return.level',return.period = rperiods)
  #"hist", "density", "rl", "trace")
  ci00=ci.fevd(fit00_0,type='return.level',return.period = rperiods)
  
  # png(paste0('/home/timok/Documents/ensex/R/graphs/tests/returnlevel',gridcell))
  par(mar=c(4.5,4.5,2.1,0))
  plot(rperiods,ci[,3],col='orange',type = 'l',lty=2,lwd=2,ylab='Return level (mm)',xlab = 'Return period (years)',log = 'x')
  lines(rperiods,ci[,1],col='orange',type = 'l',lty=2,lwd=2)
  lines(rperiods,ci[,2],col='orange')
  points(35*25*4/1:(35*25*4),sort(Extremes_gev[gridcell,],decreasing = T),col='orange',pch=1)
  lines(rperiods,ci00[,3],col='blue',type = 'l',lty=2,lwd=2)
  lines(rperiods,ci00[,1],col='blue',type = 'l',lty=2,lwd=2)
  lines(rperiods,ci00[,2],col='blue')
  points(35/1:35,sort(Extremes_gev00[gridcell,],decreasing = T),col='blue',pch=1)
  legend("topleft", legend=c("All Ensembles","GEV Ensembles", "95% Ensembles","One Ensemble","GEV fit", "95% Interval"),
         col=c("orange", "orange","orange","blue","blue","blue"), lty=c(NA,1:2,NA,1:2),lwd = c(NA,1,2,NA,1,2),pch = c(1,NA,NA,1,NA,NA),pt.cex=1,cex = 1.2)
  dev.off()
  return(  c(2*rv[,4]/rv[,2],2*rv_00[,4]/rv_00[,2],
             100*rv[,2]/rv_2,  100*rv_00[,2]/rv_2_00))
}
```



